// user actions
export const FETCHING_USER = 'FETCHING_USER'
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS'
export const FETCHING_USER_FAILURE = 'FETCHING_USER_FAILURE'
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const UNAUTHENTICATE_USER = 'UNAUTHENTICATE_USER'
export const REMOVE_FETCHING_USER = 'REMOVE_FETCHING_USER'

export const FETCHING_USER_CREDENTIALS_FROM_STORAGE = 'FETCHING_USER_CREDENTIALS_FROM_STORAGE'
export const FETCH_USER_CREDENTIALS_SUCCESS = 'FETCH_USER_CREDENTIALS_SUCCESS'
export const FETCH_USER_CREDENTIALS_FAILURE = 'FETCH_USER_CREDENTIALS_FAILURE'

export const SAVE_USER_TO_LOCAL_STORAGE = 'SAVE_USER_TO_LOCAL_STORAGE'
export const REMOVE_USER_FROM_LOCAL_STORAGE = 'REMOVE_USER_FROM_LOCAL_STORAGE'
