// user actions
export const FETCHING_USER = 'FETCHING_USER'
export const FETCHING_USER_SUCCESS = 'FETCHING_USER_SUCCESS'
export const FETCHING_USER_FAILURE = 'FETCHING_USER_FAILURE'
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const UNAUTHENTICATE_USER = 'UNAUTHENTICATE_USER'
export const REMOVE_FETCHING_USER = 'REMOVE_FETCHING_USER'
